package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	tea "github.com/charmbracelet/bubbletea"
)

func TestParseUserDirs(t *testing.T) {
	const content = `# generated by xdg-user-dirs
XDG_DESKTOP_DIR="$HOME/Namizje"
XDG_DOWNLOAD_DIR="${HOME}/Prenosi"
XDG_MUSIC_DIR="/mnt/media/music"
XDG_BROKEN_DIR="$SOMETHING/else"
not a setting
`
	got := parseUserDirs(content, "/home/k")
	want := map[string]string{
		"XDG_DESKTOP_DIR":  "/home/k/Namizje",
		"XDG_DOWNLOAD_DIR": "/home/k/Prenosi",
		"XDG_MUSIC_DIR":    "/mnt/media/music",
	}
	if len(got) != len(want) {
		t.Fatalf("parsed %v, want %v", got, want)
	}
	for k, v := range want {
		if got[k] != v {
			t.Errorf("%s = %q, want %q", k, got[k], v)
		}
	}
}

// The localized case is the point of reading user-dirs at all: gd has to land
// in ~/Prenosi on a Slovenian desktop, not in a ~/Downloads that isn't there.
func TestDefaultGotosPrefersUserDirs(t *testing.T) {
	ud := map[string]string{"XDG_DOWNLOAD_DIR": "/home/k/Prenosi"}
	ts := defaultGotos("/home/k", ud)

	byKey := map[string]string{}
	for _, tg := range ts {
		byKey[tg.key] = tg.path
	}
	if got, want := byKey["d"], "/home/k/Prenosi"; got != want {
		t.Errorf("gd = %q, want %q", got, want)
	}
	// A key XDG says nothing about still falls back to the English name.
	if got, want := byKey["p"], "/home/k/Pictures"; got != want {
		t.Errorf("gp = %q, want %q", got, want)
	}
	if got, want := byKey["h"], "/home/k"; got != want {
		t.Errorf("gh = %q, want %q", got, want)
	}
}

func TestParseGotoConfig(t *testing.T) {
	const content = `
# my own chords
w  ~/work/current
b = /mnt/backup
long  /nope        # keys longer than one character are ignored
x
`
	got := parseGotoConfig(content, "/home/k")
	want := []gotoTarget{
		{key: "w", path: "/home/k/work/current"},
		{key: "b", path: "/mnt/backup"},
	}
	if len(got) != len(want) {
		t.Fatalf("parsed %v, want %v", got, want)
	}
	for i := range want {
		if got[i].key != want[i].key || got[i].path != want[i].path {
			t.Errorf("entry %d = %+v, want %+v", i, got[i], want[i])
		}
	}
}

func TestMergeGotosReplacesInPlace(t *testing.T) {
	base := []gotoTarget{{key: "h", path: "/home/k"}, {key: "d", path: "/home/k/Downloads"}}
	user := []gotoTarget{{key: "d", path: "/mnt/big/dl"}, {key: "w", path: "/home/k/work"}}

	got := mergeGotos(base, user)
	if len(got) != 3 {
		t.Fatalf("merged to %d entries, want 3: %+v", len(got), got)
	}
	if got[1].key != "d" || got[1].path != "/mnt/big/dl" {
		t.Errorf("d should be replaced where it stood, got %+v", got[1])
	}
	if got[2].key != "w" {
		t.Errorf("new keys should be appended, got %+v", got[2])
	}
	if base[1].path != "/home/k/Downloads" {
		t.Error("mergeGotos must not write through to the base list")
	}
}

func TestKeepExistingDropsMissingAndLabels(t *testing.T) {
	dir := t.TempDir()
	real := filepath.Join(dir, "Prenosi")
	if err := os.Mkdir(real, 0o755); err != nil {
		t.Fatal(err)
	}
	file := filepath.Join(dir, "afile")
	if err := os.WriteFile(file, nil, 0o644); err != nil {
		t.Fatal(err)
	}

	got := keepExisting([]gotoTarget{
		{key: "g", label: "top of list"},              // no path — always kept
		{key: "d", path: real},                        // exists
		{key: "m", path: filepath.Join(dir, "Music")}, // missing
		{key: "f", path: file},                        // a file, not a directory
	})
	if len(got) != 2 {
		t.Fatalf("kept %+v, want only the chord and the real directory", got)
	}
	if got[1].label != "Prenosi" {
		t.Errorf("label = %q, want the directory's own name", got[1].label)
	}
}

// A desktop with its Desktop folder turned off reports XDG_DESKTOP_DIR as the
// home directory itself, which must not come back as a second gh.
func TestKeepExistingDropsDuplicatePaths(t *testing.T) {
	home := t.TempDir()
	got := keepExisting([]gotoTarget{
		{key: "h", label: "~", path: home},
		{key: "k", path: home + "/"},
	})
	if len(got) != 1 || got[0].key != "h" {
		t.Fatalf("kept %+v, want just the first chord for that directory", got)
	}
}

func TestGotoHintFallsBackToKeys(t *testing.T) {
	m := model{gotos: []gotoTarget{
		{key: "d", label: "Downloads"},
		{key: "D", label: "Documents"},
		{key: "p", label: "Pictures"},
	}}
	full := m.gotoHint(200)
	if !strings.Contains(full, "d Downloads") {
		t.Errorf("a wide terminal should name the chords: %q", full)
	}
	short := m.gotoHint(30)
	if strings.Contains(short, "Downloads") {
		t.Errorf("a narrow terminal should drop the labels: %q", short)
	}
	for _, want := range []string{"d", "D", "p", "esc cancel"} {
		if !strings.Contains(short, want) {
			t.Errorf("compact hint %q missing %q", short, want)
		}
	}
}

// gotoModel is selModel plus a known chord list, so the chord tests don't
// depend on which directories the machine running them happens to have.
func gotoModel(t *testing.T) (model, string, string) {
	t.Helper()
	m, dir := selModel(t)
	dest := filepath.Join(dir, "sub")
	if err := os.Mkdir(dest, 0o755); err != nil {
		t.Fatal(err)
	}
	m.gotos = []gotoTarget{
		{key: "g", label: "top of list"},
		{key: "d", label: "sub", path: dest},
		{key: ".", label: "start dir"},
		{key: "o", label: "other pane"},
	}
	return m, dir, dest
}

func TestGotoChordJumps(t *testing.T) {
	m, _, dest := gotoModel(t)

	m = press(t, m, keyRune('g'))
	if !m.pendingG {
		t.Fatal("g should arm the chord")
	}
	m = press(t, m, keyRune('d'))
	if m.pendingG {
		t.Error("the second key should disarm the chord")
	}
	if got := m.cur().dir; got != dest {
		t.Errorf("gd went to %q, want %q", got, dest)
	}
}

// The whole point of consuming the second key: gd must not reach the delete
// handler on its way past.
func TestGotoChordSwallowsTheSecondKey(t *testing.T) {
	m, dir, _ := gotoModel(t)
	m.gotos = nil // nothing bound, so d is not a goto either

	m = press(t, m, keyRune('j'))               // onto a.txt
	m = press(t, m, keyRune('g'), keyRune('d')) // must not be "delete"

	if m.mode == modeConfirm {
		t.Fatal("gd asked to delete something")
	}
	if _, err := os.Stat(filepath.Join(dir, "a.txt")); err != nil {
		t.Fatalf("a.txt should still be there: %v", err)
	}
	if m.status == "" {
		t.Error("an unbound chord should say so")
	}
}

func TestGotoChordKeepsGG(t *testing.T) {
	m, _, _ := gotoModel(t)
	m = press(t, m, keyRune('G'))
	if m.cur().cursor == 0 {
		t.Fatal("G should move off the top row")
	}
	m = press(t, m, keyRune('g'), keyRune('g'))
	if m.cur().cursor != 0 || m.cur().top != 0 {
		t.Errorf("gg should go to the top, cursor = %d", m.cur().cursor)
	}
}

func TestGotoStartDirAndOtherPane(t *testing.T) {
	m, dir, dest := gotoModel(t)

	// g o follows the other pane, which is still on the start directory.
	m = press(t, m, keyRune('g'), keyRune('d'))
	m = press(t, m, keyRune('g'), keyRune('o'))
	if got := m.cur().dir; got != dir {
		t.Errorf("go went to %q, want the other pane's %q", got, dir)
	}

	// g . returns to where fe was started, from wherever the pane wandered.
	m = press(t, m, keyRune('g'), keyRune('d'))
	if m.cur().dir != dest {
		t.Fatalf("setup: expected to be in %q", dest)
	}
	m = press(t, m, keyRune('g'), keyRune('.'))
	if got := m.cur().dir; got != m.startDir {
		t.Errorf("g. went to %q, want the start dir %q", got, m.startDir)
	}
}

func TestGotoChordEscCancels(t *testing.T) {
	m, dir, _ := gotoModel(t)
	m = press(t, m, keyRune('g'), tea.KeyMsg{Type: tea.KeyEsc})
	if m.pendingG {
		t.Error("esc should disarm the chord")
	}
	if m.cur().dir != dir {
		t.Error("esc should not move the pane")
	}
}

// An arrow or a tab after g is a slip, not a typo — no warning for those, but
// the pane must not move either.
func TestGotoChordIgnoresNonCharacterKeys(t *testing.T) {
	m, dir, _ := gotoModel(t)
	m = press(t, m, keyRune('g'), tea.KeyMsg{Type: tea.KeyDown})
	if m.status != "" {
		t.Errorf("an arrow after g should be silent, got %q", m.status)
	}
	if m.cur().dir != dir || m.cur().cursor != 0 {
		t.Error("an arrow after g should not move anything")
	}
}

func TestGotoReportsVanishedDestination(t *testing.T) {
	m, dir, dest := gotoModel(t)
	if err := os.Remove(dest); err != nil {
		t.Fatal(err)
	}
	m = press(t, m, keyRune('g'), keyRune('d'))
	if m.cur().dir != dir {
		t.Errorf("pane moved to a directory that is gone: %q", m.cur().dir)
	}
	if m.statusLv != lvlErr {
		t.Errorf("a missing destination should be an error, status = %q", m.status)
	}
}

// A pending g takes over the footer, so the chords never have to be memorised.
func TestGotoHintInFooter(t *testing.T) {
	m, _, _ := gotoModel(t)
	m = press(t, m, keyRune('g'))
	out := strip(m.footer())
	for _, want := range []string{"goto:", "d sub", "o other pane", "esc cancel"} {
		if !strings.Contains(out, want) {
			t.Errorf("footer %q missing %q", out, want)
		}
	}
}

func TestGotoChordsAppearInHelp(t *testing.T) {
	m, _, _ := gotoModel(t)
	var keys []string
	for _, b := range m.helpBindings() {
		keys = append(keys, b.key)
	}
	joined := strings.Join(keys, ",")
	for _, want := range []string{"g d", "g .", "g o"} {
		if !strings.Contains(joined, want) {
			t.Errorf("help is missing %q; has %s", want, joined)
		}
	}
	if strings.Contains(joined, "g g") {
		t.Error("gg is already in the static list; it should not be repeated")
	}
}
